# Generated by Django 4.0.6 on 2023-02-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_category'),
        ('store', '0005_product_category'),
    ]

    operations = [
    ]
