# Generated by Django 4.0.6 on 2023-02-13 15:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_product_category'),
        ('payment', '0002_order_ordeiterm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdeIterm',
            new_name='OrdeItem',
        ),
    ]
