# Generated by Django 4.0.6 on 2023-02-13 15:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_product_category'),
        ('payment', '0003_rename_ordeiterm_ordeitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdeItem',
            new_name='OrderItem',
        ),
    ]
