# Generated by Django 4.0.6 on 2023-02-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_ordeitem_orderitem'),
        ('payment', '0009_order_orderitem'),
    ]

    operations = [
    ]
